Repository bigcommerce/docs, pull requests merged in 2024-11, with the labels that each got.

#556 DEVDOCS-6123 [new]: Shipping / MSF International Enhancements, add channels
  docs/store-operations/shipping/msf-international-enhancements.mdx
Labels: awaiting-css-cue

#629 docs(handlebars): Add multiConcat helper to Handlebars reference
  docs/storefront/stencil/themes/context/handlebars-reference.mdx
Labels: need-SME-review

#618 Issue-602
  docs/b2b-edition/models/payment/payment.yaml
  docs/b2b-edition/specs/api-v3/payment/payment.yaml
Labels: ready for review

#623 DEVDOCS-5701: [update] add notes about emails
  docs/store-operations/orders/index.mdx
  reference/orders.v2.oas2.yml
Labels: ready for review

#625 DEVDOCS-5587: [update] add note for external_source
  reference/orders.v2.oas2.yml
Labels: ready for review

#633 DEVDOCS-6143: [update] add www settings info
  docs/storefront/headless/channels.mdx
  reference/settings.v3.yml
Labels: ready for review

#638 add new fields per DEVDOCS-6147
  docs/store-operations/emails/object-reference/combined-order-status.yml
Labels: ready for review

#651 DEVDOCS-6092: [UPDATE] change company ID to company name
  docs/b2b-edition/specs/api-v3/quote/quote.yaml
Labels: ready for review

#650 DEVDOCS-6107: [update] add note regarding Admin role
  docs/b2b-edition/specs/api-v3/authentication.yaml
Labels: ready for review

#659 DEVDOCS-6012: [update] correct path for global.js
  docs/b2b-edition/stencil.mdx
Labels: ready for review

#661 DEVDOCS-6150: [update] change limit of customer widget templates per store
  docs/storefront/widgets/index.mdx
Labels: do not merge, ready for review

#668 DEVDOCS-6151: [update] removed required label where necessary
  reference/catalog/products_catalog.v3.yml
Labels: ready for review

#677 DEVDOCS-6156: [update] remove supported types modal
  docs/store-operations/catalog/index.mdx
Labels: ready for review

#680 Feedback: [update] add required tags for query params
  docs/b2b-edition/specs/api-v3/shopping_list/shopping_list.yaml
Labels: ready for review

#683 DEVDOCS-6158: [update] update key description
  reference/widgets.v3.yml
Labels: ready for review
