Repository bigcommerce/docs, pull requests merged in 2024-07, with the labels that each got.

#330 DEVDOCS-5953: [update] add date created and date modified
  reference/locations.v3.yml
Labels: ready for review

#346 DEVDOCS-5972: [update] product videos
  docs/storefront/graphql/examples/products.mdx
Labels: ready for review

#356 DEVDOCS-5990: [update] Update Add discount to checkout schema and example
  reference/checkouts.v3.yml
Labels: ready for review

#357 DEVDOCS-6004 [update] add fields for bulk_discount_rates & fix errors in file
  docs/storefront/stencil/themes/context/object-reference/schemas/product.yml
Labels: ready for review

#355 DEVDOCS-6003 [Update] add token expiration time
  docs/store-operations/payments/index.mdx
  reference/payments/access-tokens_payments.v3.yml
Labels: ready for review

#325 [DEVDOCS-5629]: [Update] Getting Started, API Rate limits update
  docs/api-docs/getting-started/api-rate-limits.mdx
Labels: ready for review, awaiting-SME-review

#372 [DEVDOCS-5910]: [remove] Best Practices, Remove API limit content from the Development doc
  docs/start/best-practices/index.mdx
Labels: ready for review

#364 DEVDOCS-5996: [Update] channel ID is no longer a requirement for toke…
  docs/storefront/graphql/index.mdx
  reference/storefront_tokens.v3.yml
Labels: ready for review

#369 DEVDOCS-5988: [update] Update shopPath definition
  archive/storefront/blueprint/themes/global-variables.mdx
Labels: ready for review

#378 DEVDOCS-5780: [update] Added TD Online Mart
  docs/store-operations/payments/index.mdx
Labels: ready for review

#393 [No-ticket]: [new] Repo file, Add GH issues CSV to assets folder
  assets/csv/2024-07-23-12-56-27-issues.csv
Labels: no-ticket

#381 Devdocs 6030 remove store/order/transaction/updated callback
  docs/webhooks/callbacks/_all.yml
  docs/webhooks/callbacks/store_order_transaction_updated.yml
Labels: awaiting-SME-review

#365 DEVDOCS-5923: [update] add customer access token
  docs/start/authentication/graphql-storefront.mdx
  docs/storefront/graphql/index.mdx
Labels: ready for review
