Repository bigcommerce/docs, pull requests merged in 2024-12, with the labels that each got.

#666 DEVDOCS-6020: [update] added 403 response error code
  reference/promotions.v3.yml
Labels: ready for review

#701 DEVDOCS-6162: [UPDATE] remove required variant ID
  reference/carts.sf.yml
Labels: ready for review

#703 Update support.mdx
  docs/start/about/support.mdx
Labels: ready for review

#704 DEVDOCS-6161: [update] updated SKU description
  reference/catalog/products_catalog.v3.yml
Labels: ready for review

#622 DEVDOCS-5908: [update] update request to add a price adjuster
  docs/store-operations/catalog/index.mdx
  reference/catalog/product-modifiers_catalog.v3.yml
Labels: on hold, ready for review

#707 update-per-categories-feedback
  reference/catalog/products_catalog.v3.yml
Labels: ready for review

#642 doc(checkout): CHECKOUT-8739 update doc to reflect new feature of order level fees.
  reference/checkouts.sf.yml
  reference/checkouts.v3.yml
Labels: do not merge, pending-production-release

#699 DEVDOCS-6144: [update] Add examples to orders page
  docs/storefront/graphql/orders.mdx
Labels: ready for review

#545 DEVDOCS-6016 [new]: MSF International Enhancements, add product images & overrides
  docs/store-operations/catalog/graphql-admin/product-images.mdx
  docs/store-operations/catalog/msf-international-enhancements.mdx
Labels: pending-production-publishing
