Repository bigcommerce/docs, pull requests merged in 2024-06, with the labels that each got.

#307 Devdocs-5642 [update] Pages V3
  reference/pages.v3.yml
Labels: ready for review

#316 DEVDOCS-5818: update refs
  models/_root/price.yml
  models/blog/posts.yml
  models/cart/cartItems.yml
  models/common/price.yml
  models/common/product.yml
  models/customer/orders.yml
  models/product/price.yml
  models/product/related_products.yml
  models/theme_objects/_all.yml
  models/webhooks/_all.yml
Labels: ready for review

#319 (no ticket): [links] Users, update links
  docs/api-docs/channels/channel-webhooks.mdx
  docs/api-docs/customers/channel-specific-customers.mdx
  docs/api-docs/customers/customer-login-api.mdx
  docs/api-docs/customers/customers-subscribers-overview.mdx
  docs/api-docs/getting-started/about-our-api.mdx
  docs/api-docs/getting-started/rest-api-authentication.mdx
  docs/legacy/blueprint-themes/product-filtering-toolkit.mdx
  docs/stencil-docs/getting-started/transitioning-to-stencil.mdx
  docs/stencil-docs/storefront-customization/theme-accessibility.mdx
  reference/checkouts.sf.yml
  reference/tax_classes.v2.yml
Labels: dependencies

#315 [DEVDOCS-5715]: [revise] Customers V3, Add origin_channel_id to the list of read only fields
  reference/customers.v3.yml
Labels: do not merge, awaiting-SME-review

#313 CATALOG-9785: [update] Catalog, Category Images, Sort Order
  reference/catalog/categories_catalog.v3.yml
Labels: ready for review

#329 CATALOG-9786: [update] remove brand_name from response body
  reference/catalog/products_catalog.v3.yml
Labels: ready for review

#331 DEVDOCS-5383: [Update] remove All pages restrictions
  docs/integrations/scripts.mdx
Labels: ready for review

#333 DEVDOCS-5477: [Update] Added requirements for storefront checkout end…
  reference/checkouts.sf.yml
Labels: ready for review

#314 DEVDOCS-5878: [Update] graphql-cart-metafields
  docs/storefront/cart-checkout/metafields.mdx
Labels: ready for review

#334 DEVDOCS-5958: [Update] add note about multiple coupons
  reference/checkouts.v3.yml
Labels: do not merge, ready for review

#322 DEVDOCS-5953: [update] add date created and date modified query parameters
  reference/carts.v3.yml
  reference/catalog/brands_catalog.v3.yml
  reference/catalog/categories_catalog.v3.yml
  reference/catalog/product-variants_catalog.v3.yml
  reference/catalog/products_catalog.v3.yml
  reference/channels.v3.yml
  reference/customers.v3.yml
  reference/orders.v3.yml
Labels: ready for review
