Repository bigcommerce/docs, pull requests merged in 2024-08, with the labels that each got.

#411 Update graphql-storefront.mdx per Chancellor
  docs/start/authentication/graphql-storefront.mdx
Labels: ready for review

#417 DEVDOCS-6045: [update]added comparison_price and extended_comparison_price
  reference/checkouts.v3.yml
Labels: ready for review

#418 DEVDOCS-6043: [update] add Rosetta back for Macs
  docs/storefront/stencil/cli/install.mdx
Labels: ready for review

#392 DEVDOCS-6025 [update]: Get Prices (batch), add saved & reference_request fields
  reference/pricing.sf.yml
Labels: awaiting-SME-review

#430 Issue 429 [No Ticket]: add POST bulk pricing rules
  reference/catalog/products_catalog.v3.yml
Labels: need-SME-review

#438 [DEVDOCS-6071]: [update] B2B-Edition, MDX style guide corrections
  docs/b2b-edition/about/api-status-codes.mdx
  docs/b2b-edition/about/index.mdx
  docs/b2b-edition/authentication/headless-auth.mdx
  docs/b2b-edition/authentication/hosted-auth.mdx
Labels: need-SME-review

#428 [DEVDOCS-6055]: [update] CustomersV3, Clarify the relationships between Customer global settings and Customer channel settings.
  reference/customers.v3.yml
Labels: need-SME-review

#482 Issue-387: [update] remove url scheme
  reference/channels.v3.yml
Labels: ready for review
