Repository bigcommerce/docs, pull requests merged in 2024-01, with the labels that each got.

#14 DEVDOCS-5703: node sass version
  docs/api-docs/storefront/widgets/widget-builder.mdx
  docs/stencil-docs/installing-stencil-cli/installing-stencil.mdx
  docs/stencil-docs/installing-stencil-cli/stencil-cli-options-and-commands.mdx
  docs/stencil-docs/installing-stencil-cli/troubleshooting-your-setup.mdx
Labels: ready for review

#15 DEVDOCS-5689: [update] 3DS comment
  docs/api-docs/payments/payments-api-overview.mdx
Labels: ready for review

#10 DEVDOCS-5274:[update] GQL Overview, clarify no multiple sign in support
  docs/api-docs/storefront/graphql/graphql-api-overview.mdx
Labels: legacy-pr

#24 [DEVDOCS-5378]: [update] Price lists, Price lists records
  reference/price_lists.v3.yml
Labels: ready for review

#27 DEVDOCS-5718: [update] change back to node 18
  docs/stencil-docs/installing-stencil-cli/installing-stencil.mdx
Labels: ready for review

#26 DEVDOCS-5706: [update] updated order_source definition
  reference/orders.v2.oas2.yml
Labels: ready for review

#48 DEVDOCS-5729: [update] fix typo
  docs/stencil-docs/customizing-checkout/checkout-confirmation-injection.mdx
Labels: ready for review

#16 DEVDOCS-5111 : [update] add localization information
  docs/stencil-docs/customizing-checkout/custom-order-confirmation.mdx
Labels: ready for review

#8 DEVDOCS-5373: update Add Square v2
  docs/api-docs/payments/payments-api-overview.mdx
Labels: legacy-pr

#47 ISSUE-1468: [update] Catalog, remove caveat about swatch defaults
  reference/catalog/product-modifiers_catalog.v3.yml
  reference/catalog/product-variant-options_catalog.v3.yml
  reference/catalog/products_catalog.v3.yml
Labels: ready for review

#60 [DEVDOCS-5379]: [update] OrdersV2, Order/id/ PUT needs clarification about the default behavior in the description
  reference/orders.v2.oas2.yml
Labels: ready for review, awaiting-SME-review

#56 DEVDOCS-5747: [update] update steps
  docs/stencil-docs/storefront-customization/using-disqus.mdx
Labels: ready for review

#66 DEVDOCS-5705: [Update] changed ID from integer to string
  reference/carts.v3.yml
Labels: ready for review

#64 (no ticket): [update] Node Sass Sunset, CTA
  docs/api-docs/tax/tax-rates-zones.mdx
  docs/stencil-docs/installing-stencil-cli/node-sass.mdx
  reference/catalog/product-modifiers_catalog.v3.yml
  reference/catalog/product-variant-options_catalog.v3.yml
  reference/catalog/products_catalog.v3.yml
  reference/tax_rates_zones.v3.yml
  reference/tax_zone_check.v3.yml
Labels: ready for review

#67 [DEVDOCS-5709]:[update] Headless Overview, Remove broken resource link
  docs/api-docs/headless/overview.mdx
Labels: ready for review

#70 DEVDOCS-5747: [Update] clean up
  docs/stencil-docs/storefront-customization/using-disqus.mdx
Labels: ready for review

#71 no ticket-update per Jaime
  docs/stencil-docs/installing-stencil-cli/node-sass.mdx
Labels: ready for review
