Repository bigcommerce/docs, pull requests merged in 2024-09, with the labels that each got.

#492 DEVDOCS-6098: [update] added_by_promotion field
  reference/carts.v3.yml
  reference/checkouts.v3.yml
Labels: ready for review

#481 DEVDOCS-6090: [Update] Add channels
  reference/catalog/products_catalog.v3.yml
Labels: ready for review

#500 Issue-170
  docs/store-operations/settings/logs.mdx
  reference/store_logs.v3.yml
Labels: ready for review

#501 Issue-377: [update] removed trailing slash
  reference/storefront_tokens.v3.yml
Labels: ready for review

#484 DEVDOCS-6087: [update] add favicon to storefront GraphQL
  docs/storefront/graphql/examples/index.mdx
Labels: ready for review

#513 Issue-505
  reference/webhooks.v3.yml
Labels: ready for review

#507 DEVDOCS-5966: [update] correct contentType
  reference/catalog/brands_catalog.v3.yml
  reference/catalog/categories_catalog.v3.yml
  reference/catalog/product-modifiers_catalog.v3.yml
  reference/catalog/product-variants_catalog.v3.yml
  reference/catalog/products_catalog.v3.yml
Labels: ready for review

#476 DEVDOCS-6025: SF Form Fields, add requirements field for password field
  reference/form_fields.sf.yml
Labels: on hold

#523 DEVDOCS-6057: [update] is_customers_only
  reference/pages.v3.yml
Labels: ready for review

#528 cart-metafields-update
  docs/storefront/cart-checkout/metafields.mdx
Labels: ready for review

#526 DEVDOCS-6038: [update] update parent_id & tree_id definitions
  reference/catalog/category-trees_catalog.v3.yml
Labels: ready for review

#370 PROMO-1051: [add] Promotion Settings v3 REST contract
  reference/promotion_settings.v3.yml
Labels: do not merge

#521 DEVDOCS-3296: [update] add security best practices
  docs/integrations/apps/guide/publishing.mdx
Labels: ready for review

#527 Issue-512
  reference/orders.v2.oas2.yml
Labels: ready for review

#508 DEVDOCS-6042: [update] add deprecated tag
  docs/storefront/stencil/themes/context/object-reference/schemas/settings.yml
Labels: ready for review

#533 DEVDOCS-5655: [update] b2b-catalog
  docs/b2b-edition/specs/storefront/storefront/catalog.yaml
Labels: ready for review

#532 DEVDOCS-5655: [update] b2b-authentication.yml
  docs/b2b-edition/specs/storefront/authentication.yaml
Labels: ready for review

#542 DEVDOCS-5655-b2b-store
  docs/b2b-edition/specs/storefront/storefront/store.yaml
Labels: ready for review

#546 Issue-538
  docs/storefront/stencil/utils/events.mdx
Labels: ready for review

#541 DEVDOCS-5655:[update] b2b-sales-rep.yml
  docs/b2b-edition/specs/storefront/storefront/sales-rep.yaml
Labels: ready for review
