Repository bigcommerce/docs, pull requests merged in 2024-10, with the labels that each got.

#560 DEVDOCS-6111: [update] deprecate upsert form fields
  reference/customers.v3.yml
Labels: ready for review

#557 Updated security b2b authentication details
  docs/b2b-edition/specs/storefront/storefront/catalog.yaml
  docs/b2b-edition/specs/storefront/storefront/sales-rep.yaml
Labels: ready for review

#544 DEVDOCS-5655: [Update]b2b-shopping
  docs/b2b-edition/specs/storefront/storefront/shopping.yaml
  docs/b2b-edition/specs/storefront/storefront/store.yaml
Labels: ready for review

#543 DEVDOCS-5655:[update]b2b-rfq
  docs/b2b-edition/specs/storefront/storefront/rfq.yaml
Labels: ready for review

#559 DEVDOCS-6122: [update] change limit format
  reference/customers.v3.yml
Labels: ready for review

#534 DEVDOCS-5655: [update] b2b-company.yml
  docs/b2b-edition/specs/storefront/storefront/company.yaml
  docs/b2b-edition/specs/storefront/storefront/rfq.yaml
  docs/b2b-edition/specs/storefront/storefront/sales-rep.yaml
  docs/b2b-edition/specs/storefront/storefront/shopping.yaml
  docs/b2b-edition/specs/storefront/storefront/store.yaml
Labels: ready for review

#572 Issue-567
  docs/start/about/common-query-params.mdx
Labels: ready for review

#531 DEVDOCS-6110: [update] add analytics ID query to examples
  docs/storefront/graphql/examples/index.mdx
Labels: ready for review

#579 B2b 1327 s2s endpoints
  docs/b2b-edition/specs/api-v3/address/address.yaml
  docs/b2b-edition/specs/api-v3/authentication.yaml
  docs/b2b-edition/specs/api-v3/company/company.yaml
  docs/b2b-edition/specs/api-v3/invoice_management/invoice/invoice.yaml
  docs/b2b-edition/specs/api-v3/invoice_management/payment/payment.yaml
  docs/b2b-edition/specs/api-v3/invoice_management/receipt/receipt.yaml
  docs/b2b-edition/specs/api-v3/order/order.yaml
  docs/b2b-edition/specs/api-v3/payment/payment.yaml
  docs/b2b-edition/specs/api-v3/quote/quote.yaml
  docs/b2b-edition/specs/api-v3/sales_staff/sales_staff.yaml
  docs/b2b-edition/specs/api-v3/shopping_list/shopping_list.yaml
  docs/b2b-edition/specs/api-v3/super_admin/super_admin.yaml
  docs/b2b-edition/specs/api-v3/task/task.yaml
  docs/b2b-edition/specs/api-v3/user/user.yaml
Labels: ready for review

#582 Issue-581
  reference/customers.v3.yml
Labels: ready for review

#573 DEVDOCS-5928: [update] revert PR 427
  reference/customers.v3.yml
Labels: ready for review

#587 change advanced editor to standard editor
  docs/store-operations/segments/overview.mdx
  docs/store-operations/segments/promotions-api.mdx
  docs/store-operations/segments/user-guide.mdx
Labels: ready for review

#199 [DEVDOCS-5831/PAPI-2091]: Carts v3 and Store information V2, add store-level metafield's open api spec (#197)
  .idea/.gitignore
  reference/carts.v3.yml
  reference/store_information.v2.yml
Labels: do not merge, ready for review

#584 B2B Storefront review
  docs/b2b-edition/specs/storefront/storefront/catalog.yaml
  docs/b2b-edition/specs/storefront/storefront/company.yaml
Labels: ready for review

#558 DEVDOCS-6118: [update]add request example and 422 response
  reference/channels.v3.yml
Labels: do not merge, on hold

#591 DEVDOCS-4804
  docs/storefront/headless/index.mdx
Labels: ready for review

#592 Issue-583
  reference/subscribers.v3.yml
Labels: ready for review

#565 DEVDOCS-6097:[update] add "Aftership"
  reference/orders.v2.oas2.yml
Labels: ready for review

#609 DEVDOCS-5165: [update] add note about channel ID
  reference/store_content.v2.yml
Labels: ready for review

#608 DEVDOCS-5956: [update] added id:max and id:min
  reference/redirects.v3.yml
Labels: ready for review

#606 DEVDOCS-6036: [update] update date format
  reference/marketing.v2.yml
Labels: ready for review

#610 DEVDOCS-5940: [update] add order_pickup_method_id field
  reference/orders.v2.oas2.yml
Labels: ready for review

#607 DEVDOCS-5893: [update] re-order sections
  docs/store-operations/orders/invoice-templates.mdx
Labels: ready for review

#612 DEVDOCS-5959
  reference/customers.v3.yml
Labels: ready for review

#600 update create a product image request body
  reference/catalog/products_catalog.v3.yml
Labels: ready for review
