Repository bigcommerce/docs, pull requests merged in 2025-08, with the labels that each got.

#989 DEVDOCS-6413 Improve readability of modifier information in "Catalog …
  reference/catalog/product-modifiers_catalog.v3.yml
Labels: need-SME-review

#1033 DEVDOCS-6245 - S2S Payments content refresh
  docs/b2b-edition/specs/api-v3/payment/payment.yaml
Labels: ready for review, need-SME-review

#1052 DEVDOCS-6371 - Catalog Summary visibility
  docs/store-operations/catalog/index.mdx
Labels: ready for review

#1051 DEVDOCS-6410 - Remove password connected mutations
  docs/graphql-account/users.mdx
Labels: ready for review

#1057 DEVDOCS-6472 - Add sort and order parameters
  reference/store_logs.v3.yml
Labels: ready for review

#1035 DEVDOCS-6453 - add resourceId to translation gql docs
  docs/store-operations/translations/brands.mdx
  docs/store-operations/translations/categories.mdx
  docs/store-operations/translations/index.mdx
  docs/store-operations/translations/locations.mdx
Labels: ready for review, need-SME-review, awaiting-css-cue

#1068 DEVDOCS-6484 - update create coupon code response from 200 to 201
  reference/promotions.v3.yml
Labels: ready for review

#1024 DEVDOCS-6456 - add page limit to pages v3 API spec
  reference/pages.v3.yml
Labels: ready for review, awaiting-css-cue

#1029 DEVDOCS-6457 - add meta channel and mark facebook/instagram as depreciated
  reference/channels.v3.yml
Labels: ready for review, awaiting-css-cue
