Repository bigcommerce/docs, pull requests merged in 2025-05, with the labels that each got.

#945 DEVDOCS 6387 | Update broken PDF link on App Marketplace listing guid…
  docs/integrations/apps/guide/publishing.mdx
Labels: ready to merge

#944 DEVDOCS-6327 - Add cursor pagination
  docs/start/best-practices/index.mdx
Labels: ready for review

#943 DEVDOCS-6373 - Add flag to responses
  reference/checkouts.v3.yml
Labels: ready for review

#947 DEVDOCS-6376 - add customer_id field
  reference/pricing.sf.yml
Labels: ready for review

#942 DEVDOCS-6336 - Include header-based example
  docs/storefront/graphql/multi-language-support.mdx
Labels: ready for review

#936 DEVDOCS-6238 - Content Refresh - SF Super Admin
  docs/b2b-edition/specs/storefront/storefront/sales-rep.yaml
Labels: ready for review

#948 DEVDOCS-6375 - New GraphQL response headers
  docs/start/about/index.mdx
Labels: ready for review, need-SME-review

#952 DEVDOCS-6384 - Add alert about price-based sorting
  docs/storefront/graphql/index.mdx
Labels: ready for review
