Repository bigcommerce/docs, pull requests merged in 2025-04, with the labels that each got.

#905 DEVDOCS-6337: [update] added is_enabled to channels
  reference/channels.v3.yml
Labels: ready for review, need-SME-review

#909 DEVDOCS-6356: [update] version node
  docs/storefront/cart-checkout/open-checkouts/guide.mdx
Labels: ready for review

#855 DEVDOCS-6208: [update] add note for site domain tables
  reference/channels.v3.yml
  reference/sites.v3.yml
Labels: pending-production-release

#914 DEVDOCS-6344 - Clarify extraFields parameter
  docs/b2b-edition/specs/api-v3/company/company.yaml
Labels: ready for review

#913 DEVDOCS-6246 - Quotes refresh
  docs/b2b-edition/specs/api-v3/quote/quote.yaml
Labels: ready for review
