Repository bigcommerce/docs, pull requests merged in 2025-01, with the labels that each got.

#738 DEVDOCS-6187: [update] update platform limits
  docs/storefront/cart-checkout/metafields.mdx
Labels: ready for review

#721 DEVDOCS-6175: [update] update order of operations
  docs/store-operations/pricing/calculations.mdx
Labels: ready for review

#746 DEVDOCS-6186 - Remove Beta label from Form Fields Doc
  reference/form_fields.sf.yml
Labels: need-SME-review

#745 DEVDOCS-6189: [update] field restrictions
  reference/catalog/categories_catalog.v3.yml
  reference/catalog/category-trees_catalog.v3.yml
Labels: ready for review, need-SME-review

#747 DEVDOCS-6167: [new] GraphQL Admin channel locales
  docs/integrations/webhooks/events/channels.mdx
  docs/store-operations/settings/configuration.mdx
  docs/store-operations/settings/locales.mdx
Labels: ready for review, need-SME-review

#549 STRF-12557: Update Customer Login SSO documentation for new "enable_persistent_cart" field
  docs/start/authentication/customer-login.mdx
Labels: pending-production-release

#767 DEVDOCS-6196: [update] categories depth limit
  reference/catalog/categories_catalog.v3.yml
Labels: need-SME-review

#760 DEVDOCS-6084 [Update] - Added UB addendum requirement
  docs/integrations/apps/unified-billing/index.mdx
Labels: ready for review

#660 DEVDOCS-5951: [update] add storefront graphql customer updates
  docs/store-operations/customers/index.mdx
Labels: ready for review

#778 DEVDOCS-6140 [update] - Added UB requirements and limitations
  docs/integrations/apps/unified-billing/index.mdx
Labels: ready for review

#779 Added consents array to put and post request bodies
  reference/subscribers.v3.yml
Labels: ready for review

#768 DEVDOCS-6184: [update] cart downgrade feature
  docs/start/authentication/graphql-storefront.mdx
Labels: need-SME-review

#792 DEVDOCS-6204
  docs/integrations/apps/unified-billing/index.mdx
Labels: ready for review

#790 DEVDOCS-6197: [update] add concurrent limits
  reference/segments.v3.yml
Labels: ready for review, need-SME-review
